### ISSUE TITLE
Can't assign tags to issues

### ISSUE THREAD

**Issue by AlekSi** [variadico/noti#42]
CONTRIBUTING.md says:

> Try to tag your issue appropriately. If the issue is a bug report, use the bug tag; if it's a feature request use the enhancement tag.

But third-parties can't do it. Probably contributing guidelines should be changed.

**Comment by variadico** [comment]
Derp, my bad. Thank youU!!
I had no idea. _sigh_ GitHub.

Fixed: https://github.com/variadico/noti/commit/af9bc87df43c8032376b24cc5fadbd24c1ca2a29

**Comment by AlekSi** [comment]
Github uses file from default branch, `master` in this case. So contributors still see old version.

**Comment by variadico** [comment]
Yep. I know. 😃
